### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by FckYeah**
Case-sensitive OS cannot resolve your module :-)
PS: Thank you for this library 👍

### CODE REVIEW

**Comment by FckYeah** [comment]
@sunesimonsen 👋 😉

**Comment by sunesimonsen** [comment]
Nice catch @FckYeah. I don't understand how that hasn't affected me, when I developed the library, I did it on Linux.

**Comment by sunesimonsen** [comment]
Released as insection@1.2.5

**Comment by FckYeah** [comment]
@sunesimonsen it works perfectly on MacOS too, but I caught this error on Heroku.

**Comment by sunesimonsen** [comment]
Thanks for the fix.

**Pull request merged**
